## Homepage
title = "茶米遊研"
titleSeparator = "-"
titleAddition = "國外旅遊｜留學｜工作"
description = "茶米遊研是一個關於國外旅遊、留學和工作的部落格"

## Open Graph
images = ["logo.png"]
ogLocale = "zh-TW"
domainTLD = "davidchen.world"

## Twitter Cards
# twitterSite = "@gethinode"
# twitterCreator = "@markdumay"

## JSON-LD
schemaType = "Organization"
schemaName = "David Around World"
schemaAuthor = "David Chen"
#schemaAuthorTwitter = "https://twitter.com/markdumay"
#schemaAuthorLinkedIn = "https://www.linkedin.com/in/markdumay/"
#schemaAuthorGitHub = "https://github.com/markdumay"
schemaLocale = "zh-TW"
schemaLogo = "img/logo512x512.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "img/logo1280x640.png"
schemaImageWidth = 1280
schemaImageHeight = 640
# schemaTwitter = "https://twitter.com/gethinode"
# schemaLinkedIn = ""
#schemaGitHub = "https://github.com/markdumay/hugo-theme-hinode"
schemaSection = "blog"


[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

[search]
    enabled = true

[toc]
    enabled = true

[style]
    themeColor = "#b69667" #00b0f0
    themeOpacity = "10"
    themeFont = "Noto Sans TC"
    themeFontPath = "https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@100;300;400;500;700;900&display=swap"

[main]
    featurePhoto = "/img/main.png"
    logo = "/img/logo512x512.png"


[comments]
    enabled = false
    repo = "" # Replace with your repository.
    #issueTerm = "pathname" # pathname, url, title, og:title
    #label = "comment"
    # By default, light and dark mode correspond to github-light and github-dark, respectively.
    # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
    #theme = "" 
